#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("JhooApp.Resource", IsApplication=true)]

namespace JhooApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050001
			public const int sharpTypes_array = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int weapons_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int backgr = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int MainLayout = 2131099648;
			
			// aapt resource value: 0x7f06000f
			public const int affinity = 2131099663;
			
			// aapt resource value: 0x7f060009
			public const int baseattack = 2131099657;
			
			// aapt resource value: 0x7f060026
			public const int button2 = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int button3 = 2131099687;
			
			// aapt resource value: 0x7f060025
			public const int buttonCalc = 2131099685;
			
			// aapt resource value: 0x7f060022
			public const int buttonEquipment = 2131099682;
			
			// aapt resource value: 0x7f06001f
			public const int buttonItems = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int buttonLocations = 2131099680;
			
			// aapt resource value: 0x7f06001d
			public const int buttonMonsters = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int buttonQuests = 2131099678;
			
			// aapt resource value: 0x7f060023
			public const int buttonSkills = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int buttonUtils = 2131099684;
			
			// aapt resource value: 0x7f060005
			public const int cbDoubleAff = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int cbDoubleElem = 2131099654;
			
			// aapt resource value: 0x7f060011
			public const int chaos = 2131099665;
			
			// aapt resource value: 0x7f06000b
			public const int elemattack = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int elemattack2 = 2131099661;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout1 = 2131099649;
			
			// aapt resource value: 0x7f06000c
			public const int linearLayout10 = 2131099660;
			
			// aapt resource value: 0x7f060012
			public const int linearLayout11 = 2131099666;
			
			// aapt resource value: 0x7f060016
			public const int linearLayout13 = 2131099670;
			
			// aapt resource value: 0x7f060002
			public const int linearLayout2 = 2131099650;
			
			// aapt resource value: 0x7f060021
			public const int linearLayout3 = 2131099681;
			
			// aapt resource value: 0x7f06000a
			public const int linearLayout4 = 2131099658;
			
			// aapt resource value: 0x7f06000e
			public const int linearLayout5 = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int linearLayout6 = 2131099664;
			
			// aapt resource value: 0x7f060013
			public const int linearLayout7 = 2131099667;
			
			// aapt resource value: 0x7f060007
			public const int linearLayout8 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int linearLayout9 = 2131099656;
			
			// aapt resource value: 0x7f060015
			public const int sharpSelect = 2131099669;
			
			// aapt resource value: 0x7f060017
			public const int start = 2131099671;
			
			// aapt resource value: 0x7f060003
			public const int textView1 = 2131099651;
			
			// aapt resource value: 0x7f060014
			public const int textView2 = 2131099668;
			
			// aapt resource value: 0x7f060019
			public const int wEfPow = 2131099673;
			
			// aapt resource value: 0x7f06001b
			public const int wEfPowS = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int wElem = 2131099674;
			
			// aapt resource value: 0x7f06001c
			public const int wElemS = 2131099676;
			
			// aapt resource value: 0x7f060018
			public const int wPower = 2131099672;
			
			// aapt resource value: 0x7f060004
			public const int wType = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DmgCalc = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Equipment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Items = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Locations = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Monsters = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Quests = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Skills = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Utils = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040008
			public const int dmgcalc = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int equipment = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int items = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int locations = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int monsters = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int quests = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int skills = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int utils = 2130968583;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
